<?php
/**
* Class ViewAdminLTE
* @property CacheHelper $Cache
* @property FlashHelper $Flash
* @property FormHelper|CroogoFormHelper $Form
* @property HtmlHelper|CroogoHtmlHelper $Html
* @property JsBaseEngineHelper|JqueryEngineHelper|MootoolsEngineHelper|PrototypeEngineHelper $JsBaseEngine
* @property JsHelper $Js
* @property NumberHelper $Number
* @property PaginatorHelper|CroogoPaginatorHelper $Paginator
* @property RssHelper $Rss
* @property SessionHelper $Session
* @property TextHelper $Text
* @property TimeHelper $Time
* @property CkeditorHelper $Ckeditor
* @property DebugTimerHelper $DebugTimer
* @property SimpleGraphHelper $SimpleGraph
* @property TidyHelper $Tidy
* @property ToolbarHelper|FirePhpToolbarHelper|HtmlToolbarHelper $Toolbar
* @property LocationHelper $Location
* @property AclHelper $Acl
* @property RegionsHelper $Regions
* @property CommentsHelper $Comments
* @property CroogoHelper|AdminLTECroogoHelper $Croogo
* @property CustomHelper $Custom
* @property ImageHelper $Image
* @property LayoutHelper|AdminLTELayoutHelper $Layout
* @property RecaptchaHelper $Recaptcha
* @property ThemeHelper $Theme
* @property DashboardsHelper|AdminLTEDashboardsHelper $Dashboards
* @property FileManagerHelper $FileManager
* @property MenusHelper $Menus
* @property MetaHelper|AdminLTEMetaHelper $Meta
* @property NodesHelper $Nodes
* @property SettingsFormHelper|AdminLTESettingsFormHelper $SettingsForm
* @property TaxonomiesHelper $Taxonomies
* @property WysiwygHelper $Wysiwyg
* @property AdminLTEExtensionsHelper $AdminLTEExtensions
* @property AdminLTEHelper $AdminLTE
* @property CommonHelper $Common
* @property JqueryEngineHelper $JqueryEngine
* @property MootoolsEngineHelper $MootoolsEngine
* @property PrototypeEngineHelper $PrototypeEngine
* @property FirePhpToolbarHelper $FirePhpToolbar
* @property HtmlToolbarHelper $HtmlToolbar
* @property CroogoFormHelper|AdminLTEFormHelper $CroogoForm
* @property CroogoHtmlHelper|AdminLTEHtmlHelper $CroogoHtml
* @property CroogoPaginatorHelper $CroogoPaginator
* @property AdminLTECroogoHelper $AdminLTECroogo
* @property AdminLTEDashboardsHelper $AdminLTEDashboards
* @property AdminLTEFormHelper $AdminLTEForm
* @property AdminLTEHtmlHelper $AdminLTEHtml
* @property AdminLTELayoutHelper $AdminLTELayout
* @property AdminLTEMetaHelper $AdminLTEMeta
* @property AdminLTESettingsFormHelper $AdminLTESettingsForm
* @property \CrudAdminIndexHelper $CrudAdminIndex
*/
class ViewAdminLTE extends View {}
